# Generated by Django 4.0 on 2021-12-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiretime', models.TimeField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Customer.customer')),
                ('product_id', models.ManyToManyField(related_name='order', to='Product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.BigIntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='Customer.customer')),
            ],
        ),
    ]
