# Generated by Django 4.0 on 2021-12-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
            ],
            bases=('Account.user',),
        ),
    ]
